Test_BinaryTree.out : Test_BinaryTree.o BinaryTree.o
	gcc -o Test_BinaryTree.out Test_BinaryTree.o BinaryTree.o

BinaryTree.o : BinaryTree.c
	gcc -c -o BinaryTree.o BinaryTree.c
Test_BinaryTree.o : Test_BinaryTree.c
	gcc -c -o Test_BinaryTree.o Test_BinaryTree.c


